version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: app-storr-isponsorblocktv_server_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: ghcr.io/dmunozv04/isponsorblocktv:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    restart: on-failure 