version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: app-storr-maintainerr_server_1
      APP_PORT: 6246
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    container_name: app-storr-maintainerr_server_1
    image: ghcr.io/jorenn92/maintainerr:2.5.0
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-UTC}
    volumes:
      - ${APP_DATA_DIR}/data:/opt/data
    restart: on-failure

