version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: app-storr-maintainerr_server_1
      APP_PORT: 6246
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: ghcr.io/jorenn92/maintainerr:2.5.0
    user: "1000:1000"
    volumes:
      - type: bind
        source: ${APP_DATA_DIR}/data
        target: /opt/data
    environment:
      - TZ=${TZ:-UTC}
    restart: on-failure
    